services:
  - type: web
    name: samarinda-properti-gis
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "Samarinda Properti GIS"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://samarinda-properti-gis.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_SEARCH_PATH
        value: "public,extensions"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: FILESYSTEM_DISK_PUBLIC
        value: s3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: AWS_ENDPOINT
        sync: false
      - key: AWS_URL
        sync: false
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: "true"
      - key: AWS_SSL_VERIFY
        value: "false"
      - key: PORT
        value: "10000"
